version: 0.0
os: linux
files:
  - source: /
    destination: /var/tmp/testing/
hooks:
  AfterInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 1000
      runas: root
